name: AntiCheat
main: Salus\Main
version: 1.4
author: Driesboy
description: AntiCheat for MCPE
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.1, 3.0.0]
permissions:
  salus:
    description: "Allows to use all salus features."
    default: false
    children:
      salus.legitop:
        description: "A permission."
        default: false
      salus.report:
        description: "A permission."
        default: true
      salus.vanish:
        description: "A permission."
        default: op
      salus.warn:
        description: "A permission."
        default: op
